### PR TITLE
feat: reduce main page image size

### PR DESCRIPTION
**Pull request by NaMax66**
Description:
https://virtocommerce.atlassian.net/browse/ST-4973

--

QA-test:

Demo-test:

Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-764-5e7f-5e7f3141.zip

### CODE REVIEW

**Comment by asvishnyakov** [comment]
Why do you changed size of hexa images

**Comment by NaMax66** [comment]
> Why do you changed size of hexa images?

LightHouse suggestion. Actual size of hexas is larger than needed for elements containers on the page.
Look at the screenshot in the task

**Comment by asvishnyakov** [comment]
I mean `width` and `height`

**Comment by NaMax66** [comment]
> I mean `width` and `height`

Because it is reduce size and it is enough for the section context

**Pull request merged**
