### PR TITLE
feat(ST-2963): registration by invitation

### PR DESCRIPTION
**Pull request by artmakarov**
Description:
https://virtocommerce.atlassian.net/browse/ST-2963

--

QA-test: ST-2966

Demo-test:

Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-256-ec12e846.zip

### CODE REVIEW

**Review by trueboroda — APPROVED** [review]

**Comment by trueboroda** [comment]
It might be better if the user can separate the list of emails with a comma and space.
image

**Comment by trueboroda** [comment]
Check the successfully message.
image

**Review by Andrew-Orlov — APPROVED** [review]

**Comment by artmakarov** [comment]
> It might be better if the user can separate the list of emails with a comma and space. image

**Comment by artmakarov** [comment]
> Check the successful message. image

image

**Pull request merged**
