### PR TITLE
removed: parameter from createWebHistory

### PR DESCRIPTION
**Pull request by jewells07**
## Description
Fixed repetitive base URL concatenation issue (e.g., "https://localhost:2083/https://localhost:2083/...") caused by adding store URL in platform. Removed parameter from createWebHistory to handle dynamic base URLs across multiple stores.

### CODE REVIEW

**Comment by asvishnyakov** [comment]
@jewells07 Hello! Please, could you add more information about the cases this PR is fixing? Specifically, include exact steps to reproduce. Thank you!

**Comment by jewells07** [comment]
> @jewells07 Hello! Please, could you add more information about the cases this PR is fixing? Specifically, include exact steps to reproduce. Thank you!

We have implemented several changes for our multi-store setup, and one of them involves utilizing theme-based URLs.

File : router/index.ts
```
...
if (baseUrlFinal.endsWith("/")) {
    // Remove the last character using slice
    baseUrlFinal = baseUrlFinal.slice(0, -1);
  }
  const router = _createRouter({
    routes: mainRoutes,
    history: createWebHistory(baseUrlFinal),
...
```
When we add a store URL within the platform's store, it redirects to "https://localhost:2083/https://localhost:2083/account/dashboard".

**Comment by asvishnyakov** [comment]
@jewells07 But we specify store url in admin too, and it works fine: https://vcst-dev-storefront.govirto.com/

**Comment by NaMax66** [comment]
The parameter you want to remove allows hosting the app at a sub-folder of a domain like example.com/sub-folder.
It is important to keep it.

**Comment by NaMax66** [comment]
The parameter you want to remove allows hosting the app at a sub-folder of a domain like example.com/sub-folder.
It is important to keep it.

**Pull request closed without merging**
